In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive

In [ ]:
comment=pd.read_csv('/gdrive/My Drive/ASU/Courses/CIS 508 Data Mining I/Assigments/Individual Assignment 4/assignment/Comments.csv')

In [ ]:
customers=pd.read_csv('/gdrive/My Drive/ASU/Courses/CIS 508 Data Mining I/Assigments/Individual Assignment 4/assignment/Customers.csv')

In [ ]:
comment.head()

     ID                                           Comments
0  1309  Does not like the way the phone works. It is t...
1  3556  Wanted to know the nearest store location. Wan...
2  2230  Wants to know how to do text messaging. Referr...
3  2312  Asked how to disable call waiting. referred hi...
4  3327  Needs help learning how to use the phone. I su...

In [ ]:
customers.head()

   ID Sex Status  ...  LocalBilltype  LongDistanceBilltype     TARGET
0   1   F      S  ...         Budget        Intnl_discount  Cancelled
1   6   M      M  ...      FreeLocal              Standard    Current
2   8   M      M  ...      FreeLocal              Standard    Current
3  11   M      S  ...         Budget              Standard    Current
4  14   F      M  ...         Budget        Intnl_discount  Cancelled

[5 rows x 17 columns]

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

## Tokenizing Comments

In [ ]:
#make one comment to a list of words
from nltk.tokenize import word_tokenize

In [ ]:
comment['CommentsTokenized'] = comment['Comments'].apply(word_tokenize)

In [ ]:
comment

        ID  ...                                  CommentsTokenized
0     1309  ...  [Does, not, like, the, way, the, phone, works,...
1     3556  ...  [Wanted, to, know, the, nearest, store, locati...
2     2230  ...  [Wants, to, know, how, to, do, text, messaging...
3     2312  ...  [Asked, how, to, disable, call, waiting, ., re...
4     3327  ...  [Needs, help, learning, how, to, use, the, pho...
...    ...  ...                                                ...
2065  3034  ...  [Needed, help, figuring, out, his, bill, ., I,...
2066   271  ...  [He, lost, his, phone, and, called, to, cancel...
2067   783  ...  [Lost, the, directions, to, phone, and, wants,...
2068  1295  ...                    [Wants, to, change, address, .]
2069  1807  ...  [He, lost, his, phone, and, called, to, cancel...

[2070 rows x 3 columns]

In [ ]:
#Creating a new dataframe
new_comment=pd.DataFrame()
new_comment=comment.drop(columns=["CommentsTokenized","Comments"])
new_comment

        ID
0     1309
1     3556
2     2230
3     2312
4     3327
...    ...
2065  3034
2066   271
2067   783
2068  1295
2069  1807

[2070 rows x 1 columns]

## Snowball Stemmer

In [ ]:
from nltk.stem.snowball import SnowballStemmer
stemmer1 = SnowballStemmer("english")
new_comment['CommentsTokenizedStemmed'] = comment['CommentsTokenized'].apply(lambda x: [stemmer1.stem(y) for y in x]) # Stem every word.

In [ ]:
new_comment

        ID                           CommentsTokenizedStemmed
0     1309  [doe, not, like, the, way, the, phone, work, ....
1     3556  [want, to, know, the, nearest, store, locat, ....
2     2230  [want, to, know, how, to, do, text, messag, .,...
3     2312  [ask, how, to, disabl, call, wait, ., refer, h...
4     3327  [need, help, learn, how, to, use, the, phone, ...
...    ...                                                ...
2065  3034  [need, help, figur, out, his, bill, ., i, expl...
2066   271  [he, lost, his, phone, and, call, to, cancel, ...
2067   783  [lost, the, direct, to, phone, and, want, anot...
2068  1295                      [want, to, chang, address, .]
2069  1807  [he, lost, his, phone, and, call, to, cancel, ...

[2070 rows x 2 columns]

In [ ]:
new_comment['CommentsTokenizedStemmed'] = new_comment['CommentsTokenizedStemmed'].apply(lambda x: " ".join(x))

In [ ]:
new_comment

        ID                           CommentsTokenizedStemmed
0     1309  doe not like the way the phone work . it is to...
1     3556  want to know the nearest store locat . want to...
2     2230  want to know how to do text messag . refer him...
3     2312  ask how to disabl call wait . refer him to web...
4     3327  need help learn how to use the phone . i sugge...
...    ...                                                ...
2065  3034  need help figur out his bill . i explain our m...
2066   271  he lost his phone and call to cancel servic . ...
2067   783  lost the direct to phone and want anoth manual...
2068  1295                            want to chang address .
2069  1807  he lost his phone and call to cancel servic . ...

[2070 rows x 2 columns]

In [ ]:
new_comment1=comment.drop(columns=["CommentsTokenized","Comments"])
new_comment1

        ID
0     1309
1     3556
2     2230
3     2312
4     3327
...    ...
2065  3034
2066   271
2067   783
2068  1295
2069  1807

[2070 rows x 1 columns]

## Porter Stemmer

In [ ]:
from nltk.stem.porter import *
stemmer2 = PorterStemmer()
new_comment1['CommentsTokenizedStemmed'] = comment['CommentsTokenized'].apply(lambda x: [stemmer2.stem(y) for y in x]) # Stem every word.

In [ ]:
new_comment1

        ID                           CommentsTokenizedStemmed
0     1309  [doe, not, like, the, way, the, phone, work, ....
1     3556  [want, to, know, the, nearest, store, locat, ....
2     2230  [want, to, know, how, to, do, text, messag, .,...
3     2312  [ask, how, to, disabl, call, wait, ., refer, h...
4     3327  [need, help, learn, how, to, use, the, phone, ...
...    ...                                                ...
2065  3034  [need, help, figur, out, hi, bill, ., I, expla...
2066   271  [He, lost, hi, phone, and, call, to, cancel, s...
2067   783  [lost, the, direct, to, phone, and, want, anot...
2068  1295                      [want, to, chang, address, .]
2069  1807  [He, lost, hi, phone, and, call, to, cancel, s...

[2070 rows x 2 columns]

## TF-IDF matrix

In [ ]:
nltk.download('stopwords')
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
count_vect=CountVectorizer(stop_words=stop_words,lowercase=False)
TD_counts=count_vect.fit_transform(new_comment.CommentsTokenizedStemmed)
DF_TD_Counts=pd.DataFrame(TD_counts.toarray())

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
DF_TD_Counts

      0    1    2    3    4    5    6    ...  383  384  385  386  387  388  389
0       0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1       0    0    0    0    1    0    0  ...    0    0    0    0    0    0    0
2       0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3       0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4       0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2065    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2066    0    0    0    0    0    0    0  ...    0    0    1    0    0    0    0
2067    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2068    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2069    0    0    0    0    0    0    0  ...    0    0    1    0    0    0    0

[2070 rows x 390 columns]

## Using TF-IDF to find important variables

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
tfidf_count = tfidf_transformer.fit_transform(DF_TD_Counts)

In [ ]:
DF_tfidf=pd.DataFrame(tfidf_count.toarray())
DF_tfidf

      0    1    2    3        4    5    ...  384       385  386  387  388  389
0     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.000000  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.27568  0.0  ...  0.0  0.000000  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.000000  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.000000  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.000000  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...      ...  ...  ...  ...       ...  ...  ...  ...  ...
2065  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.000000  0.0  0.0  0.0  0.0
2066  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.293209  0.0  0.0  0.0  0.0
2067  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.000000  0.0  0.0  0.0  0.0
2068  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.000000  0.0  0.0  0.0  0.0
2069  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.293209  0.0  0.0  0.0  0.0

[2070 rows x 390 columns]

## Concating data

In [ ]:
data=pd.concat([DF_tfidf,customers],axis=1)

In [ ]:
data

        0    1    2  ...  LocalBilltype  LongDistanceBilltype     TARGET
0     0.0  0.0  0.0  ...         Budget        Intnl_discount  Cancelled
1     0.0  0.0  0.0  ...      FreeLocal              Standard    Current
2     0.0  0.0  0.0  ...      FreeLocal              Standard    Current
3     0.0  0.0  0.0  ...         Budget              Standard    Current
4     0.0  0.0  0.0  ...         Budget        Intnl_discount  Cancelled
...   ...  ...  ...  ...            ...                   ...        ...
2065  0.0  0.0  0.0  ...      FreeLocal              Standard  Cancelled
2066  0.0  0.0  0.0  ...         Budget              Standard  Cancelled
2067  0.0  0.0  0.0  ...         Budget              Standard  Cancelled
2068  0.0  0.0  0.0  ...      FreeLocal              Standard  Cancelled
2069  0.0  0.0  0.0  ...      FreeLocal              Standard  Cancelled

[2070 rows x 407 columns]

## Dummies

In [ ]:
feature=data.drop(columns=['TARGET','ID'])
target=data['TARGET']

In [ ]:
object_columns=list(feature.select_dtypes(include=['object']).columns)
object_columns

['Sex',
 'Status',
 'Car_Owner',
 'Paymethod',
 'LocalBilltype',
 'LongDistanceBilltype']

In [ ]:
dummy_feature=pd.get_dummies(feature,columns=object_columns)

In [ ]:
dummy_feature

        0  ...  LongDistanceBilltype_Standard
0     0.0  ...                              0
1     0.0  ...                              1
2     0.0  ...                              1
3     0.0  ...                              1
4     0.0  ...                              0
...   ...  ...                            ...
2065  0.0  ...                              1
2066  0.0  ...                              1
2067  0.0  ...                              1
2068  0.0  ...                              1
2069  0.0  ...                              1

[2070 rows x 413 columns]

In [ ]:
from sklearn import preprocessing
dummy_target=preprocessing.LabelEncoder().fit_transform(target)

In [ ]:
dummy_target

array([0, 1, 1, ..., 0, 0, 0])

## Feature Selection - Filter Method

In [ ]:
#Feature selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
filter_feature = SelectKBest(score_func=chi2, k=15).fit_transform(dummy_feature,dummy_target)
filter_feature.shape

(2070, 15)

## Feature Selection - Wrapper Method

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
knn = KNeighborsClassifier(n_neighbors=4)
sfs1 = SFS(knn, 
           k_features=15, 
           forward=True, 
           floating=False, 
           verbose=2,
           cv=5)

sfs1 = sfs1.fit(dummy_feature,dummy_target)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 413 out of 413 | elapsed:   42.1s finished

[2020-10-28 20:46:42] Features: 1/15 -- score: 0.8362318840579709[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 412 out of 412 | elapsed:   27.3s finished

[2020-10-28 20:47:09] Features: 2/15 -- score: 0.8420289855072463[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 411 out of 411 | elapsed:   27.8s finished

[2020-10-28 20:47:37] Features: 3/15 -- score: 0.8454106280193237[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 410 out of 410 | elapsed:   28.2s finished

[2020-10-28 20:48:05] Features: 4/15 -- score: 0.8526570048309179[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 409 out of 409 | elapsed:   28.5s finished

[2020-10-28 20:48:34] Features: 5/15 -- score: 0.8560386473429953[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 408 out of 408 | elapsed:   28.6s finished

[2020-10-28 20:49:03] Features: 6/15 -- score: 0.8570048309178745[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 407 out of 407 | elapsed:   29.1s finished

[2020-10-28 20:49:32] Features: 7/15 -- score: 0.8579710144927537[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 406 out of 406 | elapsed:   29.4s finished

[2020-10-28 20:50:01] Features: 8/15 -- score: 0.8589371980676328[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 405 out of 405 | elapsed:   29.8s finished

[2020-10-28 20:50:31] Features: 9/15 -- score: 0.859903381642512[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 404 out of 404 | elapsed:   30.4s finished

[2020-10-28 20:51:01] Features: 10/15 -- score: 0.8603864734299517[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 403 out of 403 | elapsed:   30.7s finished

[2020-10-28 20:51:32] Features: 11/15 -- score: 0.8608695652173912[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 402 out of 402 | elapsed:   31.3s finished

[2020-10-28 20:52:03] Features: 12/15 -- score: 0.8613526570048309[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 401 out of 401 | elapsed:   31.4s finished

[2020-10-28 20:52:35] Features: 13/15 -- score: 0.8618357487922704[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 400 out of 400 | elapsed:   32.0s finished

[2020-10-28 20:53:07] Features: 14/15 -- score: 0.8618357487922704[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 399 out of 399 | elapsed:   32.3s finished

[2020-10-28 20:53:39] Features: 15/15 -- score: 0.8618357487922704

In [ ]:
wrapper_feature_name=list(sfs1.k_feature_names_)

## Random Forest Model with Feature Selection - Filter Method

In [ ]:
from sklearn.model_selection import train_test_split
x_train,y_train,x_target,y_target=train_test_split(filter_feature,dummy_target,test_size=0.2)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train, x_target)
predict_rf = rf.predict(y_train)
predict_rf

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
#accuracy_score
print(accuracy_score(y_target,predict_rf))
#see other scores
print(classification_report(y_target,predict_rf))

0.9057971014492754
              precision    recall  f1-score   support

           0       0.87      0.90      0.88       166
           1       0.93      0.91      0.92       248

    accuracy                           0.91       414
   macro avg       0.90      0.91      0.90       414
weighted avg       0.91      0.91      0.91       414

## Random Forest Model with Feature Selection - Wrapper Method

In [ ]:
wrapper_feature=pd.DataFrame(dummy_feature[wrapper_feature_name])

In [ ]:
f_train,f_test,t_train,t_test=train_test_split(wrapper_feature,dummy_target,test_size=0.2)

In [ ]:
rf1=RandomForestClassifier()
rf1.fit(f_train,t_train)
predict_rf1 = rf1.predict(f_test)
predict_rf1

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1])

## Prediciton Score

In [ ]:
#accuracy_score
print(accuracy_score(t_test,predict_rf1))
#see other scores
print(classification_report(t_test,predict_rf1))

0.855072463768116
              precision    recall  f1-score   support

           0       0.78      0.86      0.81       153
           1       0.91      0.85      0.88       261

    accuracy                           0.86       414
   macro avg       0.84      0.86      0.85       414
weighted avg       0.86      0.86      0.86       414